### ISSUE TITLE
Block culling not working as intented

### ISSUE THREAD

**Issue by CoMakar** [cleannrooster/dungeons-perspective#11]
After the 2.0 update the mod doesn't seem to work correctly. It just adds semi-x-ray vision through walls. Frustrum culling makes it worse, it just cuts half of visible geometry.

Rooster's Guild Adventures modpack.

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/e7d71c7f-3874-4e05-bd8e-4b102b695435" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/9f100dd7-1c41-4c5b-9508-31063da1e154" />

**Comment by cleannrooster** [comment]
Hello. 
I have pushed some updates to make this better hopefully.
Please take a look.

**Comment by NemeczeK101** [comment]
> Hello. I have pushed some updates to make this better hopefully. Please take a look.

Hello I seem to have this issue still on the newest version, tested on clean modpack only with the required dependencies. Am I missing a config?
